name: hydraux_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  flutter_tabler_icons: ^1.43.0
  flutter_timezone: ^4.1.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  intl: ^0.20.2
  permission_handler: ^11.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  floor_generator: ^1.5.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
